extends Node

enum GameState {
	MENU,
	PLAYING,
	PAUSED,
	GAME_OVER
}

var current_state: GameState = GameState.MENU
## Unified coin wallet (persistent). Stored as total copper units.
## 100 copper = 1g. Use format_coins() to display, add_currency() / add_dollars()
## to earn, and bank_currency() at run end to transfer run_coins here.
var coins: int = 0
## Run-scoped coin wallet (lost on death, banked on completion).
var run_coins: int = 0
# Per-ore tracking for run summary (tile_type_id -> count/minerals)
var run_ore_counts: Dictionary = {}
var run_ore_earnings: Dictionary = {}
# Total individual ore chunks collected this run (used for capacity display)
var run_ore_chunk_count: int = 0
# Per-ore-type chunk counts (chunks physically picked up, used for inventory display)
var run_ore_chunk_counts: Dictionary = {}

# Base inventory slots per run (each ore chunk collected occupies one slot).
# Expanded by Cargo Bay spaceship upgrade and Claws (mandibles) upgrades.
const BASE_INVENTORY_SLOTS: int = 20
# Maximum number of same-type ore chunks that stack into a single inventory slot.
const STACK_SIZE: int = 32
var last_overworld_node_name: String = ""
## Path of the scene currently loaded — used by drop-in logic to route a late-joining guest
## to the same location as the host rather than always sending them to the overworld.
var current_scene_path: String = ""

# Ores allowed to spawn in the current level instance (set from MapNode.ore_types).
# Empty array means all ores can spawn (default behaviour).
var allowed_ore_types: Array = []

# Hazard types allowed to spawn in the current level instance (set from MapNode.hazard_types).
# Empty array means all hazards can spawn (default behaviour).
var allowed_hazard_types: Array = []

# Animal type for the current mine — host picks randomly and syncs to guest so
# both players see identical animals on the planet surface.
var planet_animal_type: String = ""

# Terrain generation seed for the current mine run — generated by the host and
# synced to the guest so both machines produce an identical tile layout.
var terrain_seed: int = 0

# Sky colour for the mining level — sampled from the average pixel colour of the
# selected mine node's planet sprite (set in Overworld._on_modal_confirmed).
# MiningLevel._draw() uses it to tint the sky strip and underground gradient.
var sky_color: Color = Color(0.40, 0.65, 0.90)

# Biome for the current mine run — one of "Ice", "Desert", "Rock", "Forest", "Jungle".
# Determined by the selected MapNode's planet data and passed to MiningTerrainGenerator.
var terrain_biome: String = "Rock"

# Planet size for the current mine run — one of "Small", "Medium", "Large".
# Determines the grid dimensions used by MiningLevel.
var planet_size: String = "Medium"

# Energy system
var current_energy: int = 100

func get_max_energy() -> int:
	return 100 + perk_ranks.get("paws", 0) * 25

# Settlement carry-over bonuses (applied on next mine entry, then cleared)
var settlement_energy_bonus: int = 0       # extra starting energy from Energy Cache purchase
var settlement_forager_bonus: int = 0    # kept for save compatibility; unused since ForagerSystem removed
var settlement_shroom_charges: int = 0   # Mining Shroom charges pre-purchased
var settlement_mandible_bonus: int = 0   # temporary +N claw power for one run (Claw Whetstone)

# Ladder count — persists across sessions; decremented each time player places a ladder
var ladder_count: int = 32
# Guest's ladder inventory in multiplayer — tracked on the host machine for authoritative validation.
# On the guest machine, ladder_count itself serves as the guest's personal inventory.
var guest_ladder_count: int = 32

# Currently selected hotbar slot: 0 = pickaxe, 1 = ladder, 2–9 = empty
var selected_hotbar_slot: int = 0

# Equipped followers (independent toggles)
var equipped_leaf: bool = false
var equipped_ice: bool = false
# Stub companion equipped states — keyed by companion id (see HatMenu.COMPANIONS)
var equipped_companions: Dictionary = {}

# Equipped trinkets (independent toggles, persistent)
var trinket_paraglider: bool = false          # Glide + no fall damage
var trinket_jet_boots: bool = false           # Mid-air boost after double jump
var trinket_stone_of_regen: bool = false      # +1 HP every 4 seconds
var trinket_spring_boots: bool = false        # +2m jump height
var trinket_jumping_bean: bool = false        # +20% mining power
var trinket_sneakers: bool = false            # Free sprint (no energy cost)
var trinket_gecko_gloves: bool = false        # Wall slide to slow descent
var trinket_boots_of_sprinting: bool = false  # +1 energy/sec while walking
var trinket_cube_of_curing: bool = false      # Immune to plasma burn
var trinket_scuba_helmet: bool = false        # Immune to gas clouds
var trinket_magnet: bool = false              # Attract ore within 4 tiles
var trinket_cosmic_radiation: bool = false    # Random HP/energy bitflips
var trinket_curse_of_core: bool = false       # -1 HP every 8 sec underground

# Selected class for the current save (set during class selection on new game).
# Empty string means no class chosen (legacy saves / multiplayer guest).
var player_class: String = ""

# Cat customization — base tint (white = no tint) and outline colour (default dark #2B222A)
var cat_color: Color = Color.WHITE
var cat_outline_color: Color = Color("2b222a")

# Legacy upgrade levels — kept at 0 (stat getters now use perk_ranks instead).
# These vars remain for save-file backwards-compatibility and multiplayer RPC
# signatures.  Do not increment them directly; use the perk tree instead.
var carapace_level: int = 0
var legs_level: int = 0
var mandibles_level: int = 0
var mineral_sense_level: int = 0
var claws_level: int = 0
var ladder_climb_speed_level: int = 0
var mining_reach_level: int = 0

# ---------------------------------------------------------------------------
# Perk Tree — experience, levels, and perk ranks
# ---------------------------------------------------------------------------
var player_xp: int = 0          # XP within the current level (resets on level-up)
var player_level: int = 1       # Current player level (1-indexed)
var perk_points: int = 0        # Unspent perk points (1 awarded per level-up)
## Maps perk id (String) -> current rank (int).  Missing key = rank 0.
var perk_ranks: Dictionary = {}

# ---------------------------------------------------------------------------
# Global Progress — shared across all saves, stored in a separate file.
# Used to unlock cosmetics (cat colors, companions) independent of save slots.
# ---------------------------------------------------------------------------
var global_player_xp: int = 0      # XP within the current global level
var global_player_level: int = 1   # Global player level (1-indexed)

# Playtime incentive — awards 1% of the XP needed for the next global level every 25 minutes.
# Runs regardless of game state so menu time counts too.  Persisted in global_progress.json.
const PLAYTIME_XP_INTERVAL: float = 1500.0  # 25 minutes in seconds
var playtime_xp_timer: float = 0.0

# Gem socketing system — gems collected as items, socketed for passive bonuses
var gem_count: int = 0                       # unspent gems in the colony's stockpile
const GEM_SOCKET_COST: int = 3              # gems required to fill one socket slot
var carapace_gem_socketed: bool = false      # +1 max HP
var legs_gem_socketed: bool = false          # +25 max energy, +15 move speed
var mandibles_gem_socketed: bool = false     # +4 mining power
var sense_gem_socketed: bool = false         # +3 sonar ping radius

# Spaceship Upgrade system — permanent ship upgrades unlocked by milestone conditions.
# Unlock conditions are checked at runtime; build costs are spent from dollars.
## Spaceship upgrade costs in copper (100 copper = 1g).
## 20000 copper = 200g, 15000 = 150g, 30000 = 300g, 25000 = 250g.
const SHIP_COST_WARP_DRIVE: int       = 20000  # unlocks when total_coins_banked >= 50000
const SHIP_COST_CARGO_BAY: int        = 15000  # unlocks when bosses_defeated_total >= 1
const SHIP_COST_LONG_SCANNER: int     = 30000  # unlocks when total_coins_banked >= 100000
const SHIP_COST_GEM_REFINERY: int     = 25000
const SHIP_COST_TRADE_AMPLIFIER: int  = 20000  # unlocks when deepest_row_reached >= 96

# Cumulative milestone trackers (persisted to save)
var total_coins_banked: int = 0          # sum of all coins ever banked (in copper)
var bosses_defeated_total: int = 0       # total boss encounters won
var deepest_row_reached: int = 0         # deepest grid row ever reached
var total_playtime_seconds: float = 0.0  # total seconds played (accumulated while PLAYING)

# Spaceship upgrade built flags (persisted to save)
var warp_drive_built: bool = false       # 2x caravan travel speed on overworld
var cargo_bay_built: bool = false        # +25 ore carrying capacity per run
var long_scanner_built: bool = false     # always show both asteroid mines on overworld
var gem_refinery_built: bool = false     # +1 bonus gem per gem ore mined
var trade_amplifier_built: bool = false  # +25% dollar payout when selling bars

# Father's Debt — story goal tracked across all runs (persisted to save)
## Total debt owed: 50,000,000 copper (5000g). Paid off incrementally via the Clowder menu.
const FATHERS_DEBT_TOTAL: int = 50_000_000
var debt_paid: int = 0  # copper amount paid toward the father's debt so far

# Planet progression tracking (persisted to save)
var has_completed_tier_1_mine: bool = false       # True when player completes any Mine 1/2/3
var has_completed_tier_2_settlement: bool = false # True when player completes any Settlement 3/4

# Onboarding flags (persisted to save)
var has_seen_overworld_hint: bool = false  # Suppresses first-visit overworld guidance after first display
var has_completed_first_run: bool = false  # True after first successful mine exit; gates tutorial hints
var has_seen_intro: bool = false           # True after the narrative intro plays; prevents replay on continue

# Current node type for the active mine/settlement run (transient, not persisted)
var current_node_type: int = 0  # MapNode.NodeType value of the node being mined/visited

# ---------------------------------------------------------------------------
# Mid-run save state — allows seamless resume after quitting mid-mine.
# All fields are persisted to the active slot and cleared on run end or death.
# ---------------------------------------------------------------------------
## True while the player is inside a mining level run.
## SaveManager uses this to know whether to offer/auto-apply a mid-run restore.
var run_is_in_mining_level: bool = false
## The overworld node name that started this run — used to match the saved run
## against the node the player clicks when resuming (prevents accidental resume
## if they click a different mine).
var run_node_name: String = ""
## Player world-space position captured at the last auto-save tick.
var run_player_pos_x: float = 0.0
var run_player_pos_y: float = 0.0
## Player health captured at the last auto-save tick.
var run_player_health: float = 0.0
## Sparse diff of every grid cell that changed from the procedurally-generated
## baseline.  Stored as Array of [col: int, row: int, tile_type: int] triples.
## Applied on top of a freshly-seeded terrain to recreate the exact mine state.
var run_terrain_changes: Array = []

const SAVE_PATH = "user://save_data.json"

func _ready() -> void:
	# Legacy load_game() removed — SaveManager now handles slot-based persistence.
	# On first boot, SaveManager._migrate_legacy_save() imports the old file.
	NetworkManager.guest_connected.connect(_on_guest_connected)
	get_tree().set_auto_accept_quit(false)

func _notification(what: int) -> void:
	if what == NOTIFICATION_WM_CLOSE_REQUEST:
		# Ask MiningLevel (if active) to flush its current terrain state into
		# GameManager before we snapshot — ensures the save reflects the exact
		# moment the player quit rather than the last 30-second auto-save tick.
		if run_is_in_mining_level:
			EventBus.mining_state_capture_requested.emit()
		if SaveManager.active_slot >= 0:
			SaveManager.save_active_slot()
		get_tree().quit()

func _process(delta: float) -> void:
	if current_state == GameState.PLAYING:
		total_playtime_seconds += delta

	playtime_xp_timer += delta
	if playtime_xp_timer >= PLAYTIME_XP_INTERVAL:
		playtime_xp_timer -= PLAYTIME_XP_INTERVAL
		var xp_reward: int = maxi(1, PerkSystem.xp_for_next_level(global_player_level) / 100)
		_add_global_xp_only(xp_reward)
	EventBus.playtime_xp_progress.emit(playtime_xp_timer / PLAYTIME_XP_INTERVAL)

## Format a copper amount as a human-readable coin string.
## 100 copper = 1g. Examples: 12345 → "123g", 500 → "5g", 7 → "0g", 0 → "0g"
static func format_coins(copper: int) -> String:
	return "%dg" % maxi(0, copper / 100)

## Add copper directly to the run wallet (use for ore pickups, bonuses, etc.).
## Callers may pass old "mineral unit" amounts — multiply by 100 to get copper.
func add_currency(amount: int) -> void:
	run_coins += amount * 100
	EventBus.coins_changed.emit(run_coins)

## Add copper directly to the persistent wallet (use for smeltery sales, etc.).
## Callers may pass old "dollar" amounts — multiply by 100 to get copper.
func add_dollars(amount: int) -> void:
	coins += amount * 100
	EventBus.coins_changed.emit(coins)
	save_game()

## Add a copper amount directly to the persistent wallet without any conversion.
## Use this when the value is already in copper (e.g. computed from copper-denominated prices).
func add_coins_direct(copper: int) -> void:
	coins += copper
	EventBus.coins_changed.emit(coins)
	save_game()

func track_ore_mined(tile_type: int, minerals: int) -> void:
	run_ore_counts[tile_type] = run_ore_counts.get(tile_type, 0) + 1
	run_ore_earnings[tile_type] = run_ore_earnings.get(tile_type, 0) + minerals

func track_ore_chunk_collected() -> void:
	run_ore_chunk_count += 1

func track_ore_chunk_collected_by_type(ore_type: int) -> void:
	run_ore_chunk_count += 1
	run_ore_chunk_counts[ore_type] = run_ore_chunk_counts.get(ore_type, 0) + 1

func bank_currency() -> void:
	# Award XP for successfully banking minerals (1 XP per silver-equivalent)
	if run_coins > 0:
		add_xp(run_coins / 100)
	total_coins_banked += run_coins
	coins += run_coins
	run_coins = 0
	EventBus.coins_changed.emit(0)
	# Always persist XP after banking — level-up saves already fire inside
	# add_xp(), but sub-level progress would otherwise be lost until next load.
	SaveManager.save_active_slot()

func change_state(new_state: GameState) -> void:
	current_state = new_state
	EventBus.game_state_changed.emit(current_state)

func start_game() -> void:
	change_state(GameState.PLAYING)
	# In multiplayer, host sends upgrade state to guest before loading overworld
	if NetworkManager.is_multiplayer_session and NetworkManager.is_host and NetworkManager.guest_peer_id > 0:
		rpc_start_game_as_guest.rpc_id(NetworkManager.guest_peer_id,
			carapace_level, legs_level, mandibles_level, mineral_sense_level, claws_level,
			ladder_climb_speed_level, mining_reach_level,
			carapace_gem_socketed, legs_gem_socketed, mandibles_gem_socketed, sense_gem_socketed,
			warp_drive_built, cargo_bay_built, long_scanner_built, gem_refinery_built, trade_amplifier_built)
	# Show narrative intro on first new game (singleplayer only)
	if not has_seen_intro and not NetworkManager.is_multiplayer_session:
		# Pre-load the overworld in the background while the intro is playing
		# so there is no delay or flash when switching scenes afterwards.
		const OVERWORLD := "res://src/levels/Overworld.tscn"
		ResourceLoader.load_threaded_request(OVERWORLD)
		var intro := IntroSequence.new()
		get_tree().root.add_child(intro)
		await SceneTransition.fade_from_black(0.5)
		await intro.finished
		has_seen_intro = true
		save_game()
		# The intro leaves a solid black background on screen; take it over with
		# SceneTransition before the intro node is freed so there is no flash.
		SceneTransition.color_rect.modulate.a = 1.0
		SceneTransition.is_transitioning = true
		# Block until the background load is done (almost always instant by now).
		while ResourceLoader.load_threaded_get_status(OVERWORLD) == ResourceLoader.THREAD_LOAD_IN_PROGRESS:
			await get_tree().process_frame
		var packed: PackedScene = ResourceLoader.load_threaded_get(OVERWORLD)
		current_scene_path = OVERWORLD
		get_tree().change_scene_to_packed(packed)
		await get_tree().create_timer(0.1).timeout
		await SceneTransition.fade_from_black(0.5)
		return
	load_overworld()

## Called on guest by host to apply kit/upgrade state before the game starts.
## Scene loading is handled separately by rpc_load_overworld_as_guest, which is
## sent immediately after this RPC via load_overworld().  Keeping state sync and
## scene loading in separate RPCs prevents the guest from loading Overworld twice.
@rpc("authority", "call_remote", "reliable")
func rpc_start_game_as_guest(carapace_lvl: int, legs_lvl: int, mandibles_lvl: int,
		mineral_sense_lvl: int, claws_lvl: int, ladder_climb_lvl: int, mining_reach_lvl: int,
		carapace_gem: bool, legs_gem: bool, mandibles_gem: bool, sense_gem: bool,
		warp: bool, cargo: bool, scanner: bool, refinery: bool, amplifier: bool) -> void:
	carapace_level = carapace_lvl
	legs_level = legs_lvl
	mandibles_level = mandibles_lvl
	mineral_sense_level = mineral_sense_lvl
	claws_level = claws_lvl
	ladder_climb_speed_level = ladder_climb_lvl
	mining_reach_level = mining_reach_lvl
	carapace_gem_socketed = carapace_gem
	legs_gem_socketed = legs_gem
	mandibles_gem_socketed = mandibles_gem
	sense_gem_socketed = sense_gem
	warp_drive_built = warp
	cargo_bay_built = cargo
	long_scanner_built = scanner
	gem_refinery_built = refinery
	trade_amplifier_built = amplifier
	EventBus.multiplayer_guest_kit_updated.emit()
	change_state(GameState.PLAYING)
	# Scene transition handled by the following rpc_load_overworld_as_guest call

## Drop-in: called when a guest connects while the host is already in-game.
## Sends the guest the host's kit and routes them to the host's current location.
func _on_guest_connected(peer_id: int) -> void:
	if not NetworkManager.is_host or current_state != GameState.PLAYING:
		return
	if "MiningLevel" in current_scene_path:
		# Host is mid-mine — send guest directly into the same mine.
		rpc_drop_in_to_mine_as_guest.rpc_id(peer_id,
			carapace_level, legs_level, mandibles_level, mineral_sense_level, claws_level,
			ladder_climb_speed_level, mining_reach_level,
			carapace_gem_socketed, legs_gem_socketed, mandibles_gem_socketed, sense_gem_socketed,
			warp_drive_built, cargo_bay_built, long_scanner_built, gem_refinery_built, trade_amplifier_built,
			current_scene_path, current_energy,
			sky_color.r, sky_color.g, sky_color.b,
			allowed_ore_types, allowed_hazard_types,
			planet_animal_type, terrain_seed, terrain_biome, planet_size)
	else:
		# Host is on the overworld (or a settlement) — sync kit then load the
		# overworld on the guest.  Planet config (names, positions, sprite frames)
		# is synced via the request/response already built into Overworld._ready():
		# the guest calls rpc_request_planet_config once its scene is ready, and
		# the host responds with rpc_apply_planet_config.
		rpc_start_game_as_guest.rpc_id(peer_id,
			carapace_level, legs_level, mandibles_level, mineral_sense_level, claws_level,
			ladder_climb_speed_level, mining_reach_level,
			carapace_gem_socketed, legs_gem_socketed, mandibles_gem_socketed, sense_gem_socketed,
			warp_drive_built, cargo_bay_built, long_scanner_built, gem_refinery_built, trade_amplifier_built)
		rpc_load_overworld_as_guest.rpc_id(peer_id)

func pause_game() -> void:
	change_state(GameState.PAUSED)

func lose_run() -> void:
	run_coins = 0
	run_ore_counts.clear()
	run_ore_earnings.clear()
	run_ore_chunk_count = 0
	run_ore_chunk_counts.clear()
	# Clear mid-run save state so the player starts fresh on their next mine entry.
	run_is_in_mining_level = false
	run_terrain_changes.clear()
	run_node_name = ""
	run_player_pos_x = 0.0
	run_player_pos_y = 0.0
	run_player_health = 0.0
	EventBus.coins_changed.emit(0)
	# Clear planet config so the overworld re-randomizes on next visit
	if not NetworkManager.is_multiplayer_session or NetworkManager.is_host:
		SaveManager.clear_active_slot_run_data()
	if NetworkManager.is_multiplayer_session and NetworkManager.is_host and NetworkManager.guest_peer_id > 0:
		rpc_lose_run_as_guest.rpc_id(NetworkManager.guest_peer_id)
	await _transition_to_scene("res://src/levels/Overworld.tscn")

@rpc("authority", "call_remote", "reliable")
func rpc_lose_run_as_guest() -> void:
	run_coins = 0
	run_ore_counts.clear()
	run_ore_earnings.clear()
	run_ore_chunk_count = 0
	run_ore_chunk_counts.clear()
	EventBus.coins_changed.emit(0)
	await _transition_to_scene("res://src/levels/Overworld.tscn")

func complete_run() -> void:
	# Run completed — clear the mid-run save state so a fresh run starts next time.
	run_is_in_mining_level = false
	run_terrain_changes.clear()
	run_node_name = ""
	run_player_pos_x = 0.0
	run_player_pos_y = 0.0
	run_player_health = 0.0
	if not has_completed_first_run:
		has_completed_first_run = true
		save_game()
	if NetworkManager.is_multiplayer_session and NetworkManager.is_host and NetworkManager.guest_peer_id > 0:
		rpc_complete_run_as_guest.rpc_id(NetworkManager.guest_peer_id, run_coins)
	var summary_scene = load("res://src/ui/RunSummary.tscn")
	var summary = summary_scene.instantiate()
	get_tree().root.add_child(summary)
	# Note: RunSummary handles banking and returning to Overworld

@rpc("authority", "call_remote", "reliable")
func rpc_complete_run_as_guest(final_coins: int) -> void:
	run_coins = final_coins
	EventBus.coins_changed.emit(run_coins)
	var summary_scene = load("res://src/ui/RunSummary.tscn")
	var summary = summary_scene.instantiate()
	get_tree().root.add_child(summary)

func load_mining_level(scene_path: String = "") -> void:
	var path := scene_path if scene_path != "" else "res://src/levels/MiningLevel.tscn"

	# Resume detection (single-player only): if we have a saved mid-run state for
	# this exact overworld node, skip resetting run currency / energy so MiningLevel
	# can restore the terrain diff and player position on top of the seeded terrain.
	var is_resume := (
		not NetworkManager.is_multiplayer_session
		and run_is_in_mining_level
		and run_node_name != ""
		and run_node_name == last_overworld_node_name
	)

	if not is_resume:
		# Fresh run — reset all per-run state.
		run_is_in_mining_level = false
		run_terrain_changes.clear()
		run_node_name = ""
		run_player_pos_x = 0.0
		run_player_pos_y = 0.0
		run_player_health = 0.0
		run_coins = 0
		run_ore_counts.clear()
		run_ore_earnings.clear()
		run_ore_chunk_count = 0
		run_ore_chunk_counts.clear()
		current_energy = get_max_energy()

		# Apply settlement carry-over bonuses then clear them
		if settlement_energy_bonus > 0:
			current_energy = mini(current_energy + settlement_energy_bonus, get_max_energy() + settlement_energy_bonus)
			settlement_energy_bonus = 0
		# shroom / mandible / forager bonuses are consumed by MiningLevel on entry

		# Generate a fresh terrain seed for this run.
		if NetworkManager.is_multiplayer_session and NetworkManager.is_host:
			var _types := ["Chicken", "Sheep", "Pig"]
			planet_animal_type = _types[randi() % _types.size()]
			terrain_seed = randi()
		elif not NetworkManager.is_multiplayer_session:
			terrain_seed = randi()
	# else (resume): terrain_seed, current_energy, run_coins, run_ore_chunk_counts,
	# and run_terrain_changes are all already set from the loaded save data.

	EventBus.coins_changed.emit(run_coins)
	EventBus.energy_changed.emit(current_energy, get_max_energy())

	# In multiplayer, tell guest to load the same mine with the same starting state.
	# Resuming mid-run is not supported in co-op; guests always get a fresh run state.
	if NetworkManager.is_multiplayer_session and NetworkManager.is_host and NetworkManager.guest_peer_id > 0:
		rpc_load_mine_as_guest.rpc_id(NetworkManager.guest_peer_id, path,
			current_energy, sky_color.r, sky_color.g, sky_color.b,
			allowed_ore_types, allowed_hazard_types,
			settlement_shroom_charges, settlement_mandible_bonus,
			planet_animal_type, terrain_seed, terrain_biome, planet_size)
	change_state(GameState.PLAYING)
	await _transition_to_scene(path)

## Guest RPC: mirror the host's mine-entry state then load the same level.
@rpc("authority", "call_remote", "reliable")
func rpc_load_mine_as_guest(path: String, start_energy: int,
		sky_r: float, sky_g: float, sky_b: float,
		ore_types: Array, hazard_types: Array,
		shroom_charges: int, mandible_bonus: int,
		animal_type: String, seed_value: int,
		biome: String = "Rock", size: String = "Medium") -> void:
	run_coins = 0
	run_ore_counts.clear()
	run_ore_earnings.clear()
	run_ore_chunk_count = 0
	run_ore_chunk_counts.clear()
	current_energy = start_energy
	sky_color = Color(sky_r, sky_g, sky_b)
	allowed_ore_types = ore_types.duplicate()
	allowed_hazard_types = hazard_types.duplicate()
	settlement_shroom_charges = shroom_charges
	settlement_mandible_bonus = mandible_bonus
	planet_animal_type = animal_type
	terrain_seed = seed_value
	terrain_biome = biome
	planet_size = size
	EventBus.coins_changed.emit(0)
	EventBus.energy_changed.emit(current_energy, get_max_energy())
	await _transition_to_scene(path)

## Guest RPC: drop in to the host's active mine run mid-session.
## Applies the host's kit then loads the same MiningLevel the host is already in.
@rpc("authority", "call_remote", "reliable")
func rpc_drop_in_to_mine_as_guest(carapace_lvl: int, legs_lvl: int, mandibles_lvl: int,
		mineral_sense_lvl: int, claws_lvl: int, ladder_climb_lvl: int, mining_reach_lvl: int,
		carapace_gem: bool, legs_gem: bool, mandibles_gem: bool, sense_gem: bool,
		warp: bool, cargo: bool, scanner: bool, refinery: bool, amplifier: bool,
		mine_path: String, start_energy: int,
		sky_r: float, sky_g: float, sky_b: float,
		ore_types: Array, hazard_types: Array,
		animal_type: String, seed_value: int,
		biome: String = "Rock", size: String = "Medium") -> void:
	carapace_level = carapace_lvl
	legs_level = legs_lvl
	mandibles_level = mandibles_lvl
	mineral_sense_level = mineral_sense_lvl
	claws_level = claws_lvl
	ladder_climb_speed_level = ladder_climb_lvl
	mining_reach_level = mining_reach_lvl
	carapace_gem_socketed = carapace_gem
	legs_gem_socketed = legs_gem
	mandibles_gem_socketed = mandibles_gem
	sense_gem_socketed = sense_gem
	warp_drive_built = warp
	cargo_bay_built = cargo
	long_scanner_built = scanner
	gem_refinery_built = refinery
	trade_amplifier_built = amplifier
	EventBus.multiplayer_guest_kit_updated.emit()
	run_coins = 0
	run_ore_counts.clear()
	run_ore_earnings.clear()
	run_ore_chunk_count = 0
	run_ore_chunk_counts.clear()
	current_energy = start_energy
	sky_color = Color(sky_r, sky_g, sky_b)
	allowed_ore_types = ore_types.duplicate()
	allowed_hazard_types = hazard_types.duplicate()
	planet_animal_type = animal_type
	terrain_seed = seed_value
	terrain_biome = biome
	planet_size = size
	EventBus.coins_changed.emit(0)
	EventBus.energy_changed.emit(current_energy, get_max_energy())
	change_state(GameState.PLAYING)
	await _transition_to_scene(mine_path)

func load_settlement_level(scene_path: String) -> void:
	# Visit a settlement without resetting run state — player keeps banked minerals
	change_state(GameState.PLAYING)
	await _transition_to_scene(scene_path)

func load_overworld() -> void:
	change_state(GameState.PLAYING)
	if NetworkManager.is_multiplayer_session and NetworkManager.is_host and NetworkManager.guest_peer_id > 0:
		rpc_load_overworld_as_guest.rpc_id(NetworkManager.guest_peer_id)
	await _transition_to_scene("res://src/levels/Overworld.tscn")

@rpc("authority", "call_remote", "reliable")
func rpc_load_overworld_as_guest() -> void:
	change_state(GameState.PLAYING)
	await _transition_to_scene("res://src/levels/Overworld.tscn")

func _transition_to_scene(scene_path: String) -> void:
	await SceneTransition.fade_to_black(0.5)
	current_scene_path = scene_path
	get_tree().change_scene_to_file(scene_path)
	await get_tree().create_timer(0.1).timeout
	await SceneTransition.fade_from_black(0.5)

func upgrade_carapace() -> void:
	carapace_level += 1
	save_game()

func upgrade_legs() -> void:
	legs_level += 1
	save_game()

func upgrade_mandibles() -> void:
	mandibles_level += 1
	save_game()
	EventBus.coins_changed.emit(run_coins)

func upgrade_mineral_sense() -> void:
	mineral_sense_level += 1
	save_game()

func upgrade_claws() -> void:
	claws_level += 1
	save_game()

func upgrade_ladder_climb_speed() -> void:
	ladder_climb_speed_level += 1
	save_game()

func upgrade_mining_reach() -> void:
	mining_reach_level += 1
	save_game()

func get_sonar_ping_radius() -> float:
	return 4.0 + perk_ranks.get("whiskers", 0) * 3.0

## Number of inventory slots available per run (slot-based; each ore chunk uses one slot).
## Boosted by Cargo Bay spaceship upgrade, Cargo Claws perk, Satchel, Deep Satchel, and Packrat perks.
func get_ore_capacity() -> int:
	return (BASE_INVENTORY_SLOTS
		+ (5 if cargo_bay_built else 0)
		+ perk_ranks.get("cargo", 0) * 2
		+ perk_ranks.get("satchel", 0) * 3
		+ perk_ranks.get("deep_satchel", 0) * 5
		+ perk_ranks.get("packrat", 0) * 3)

## Maximum number of same-type ore chunks per inventory slot.
## Boosted by Stack Mastery and Packrat perks.
func get_max_stack_size() -> int:
	return STACK_SIZE + perk_ranks.get("stack_mastery", 0) * 8 + perk_ranks.get("packrat", 0) * 10

## Number of slots currently occupied, counting stacks of up to get_max_stack_size() chunks per slot.
## Same ore type chunks stack together; one slot holds up to get_max_stack_size() of a single type.
func get_stacked_slots_used() -> int:
	var total: int = 0
	var stack_size: int = get_max_stack_size()
	for count: int in run_ore_chunk_counts.values():
		total += ceili(float(count) / float(stack_size))
	return total

## Returns true when every inventory slot is occupied and no more ore can be picked up.
func is_inventory_full() -> bool:
	return get_stacked_slots_used() >= get_ore_capacity()

## Caravan travel speed multiplier on the overworld (boosted by Warp Drive and Thrusters perk).
func get_ship_speed_mult() -> float:
	var base: float = 2.0 if warp_drive_built else 1.0
	return base * (1.0 + perk_ranks.get("thrusters", 0) * 0.15)

## Number of extra mining planets added to the star chart (from Nav Charts perk).
func get_extra_mine_planets() -> int:
	return perk_ranks.get("nav_charts", 0) / 2

## Number of ore types revealed in the planet preview before landing (from Ore Scanner perk).
func get_ore_preview_slots() -> int:
	return perk_ranks.get("ore_scanner", 0)

## Warp cost reduction fraction from Warp Mastery perk (0.0–0.45).
func get_warp_cost_reduction() -> float:
	return perk_ranks.get("warp_mastery", 0) * 0.15

## Bonus gems awarded per gem ore mined (boosted by Gem Refinery).
func get_gem_mine_bonus() -> int:
	return 1 if gem_refinery_built else 0

## Dollar sell multiplier for smeltery bars (boosted by Trade Amplifier).
func get_dollar_sell_mult() -> float:
	return 1.25 if trade_amplifier_built else 1.0

func get_sonar_ping_energy_cost() -> int:
	return maxi(1, 5 - perk_ranks.get("whiskers", 0))

func get_ladder_climb_speed() -> float:
	return 420.0 + perk_ranks.get("ladder_mastery", 0) * 50.0

func get_mining_reach() -> float:
	return 4.5 + perk_ranks.get("reach", 0) * 0.75

func get_max_health() -> int:
	return 3 + perk_ranks.get("pelt", 0) + perk_ranks.get("nine_lives", 0) * 2

func get_max_speed() -> float:
	return 300.0 + perk_ranks.get("paws", 0) * 30.0

func get_mandibles_power() -> int:
	var base: int = 5 + perk_ranks.get("claws", 0) * 3
	if trinket_jumping_bean:
		return int(base * 1.2)
	return base

## Bonus lucky strike chance from Deep Veins perk (additive, 0.0–0.25).
func get_lucky_strike_bonus() -> float:
	return perk_ranks.get("deep_veins", 0) * 0.05

## Ore mineral yield multiplier from Motherlode perk (1.0 = no bonus).
func get_ore_yield_mult() -> float:
	return 1.0 + perk_ranks.get("motherlode", 0) * 0.10

## Boss energy drain multiplier reduction from Iron Hide perk.
## Returns a value in [0.0, 0.5]; subtract from drain multiplier.
func get_boss_drain_reduction() -> float:
	return perk_ranks.get("iron_hide", 0) * 0.10

## Additional upward jump velocity from Agility perk (negative = higher jump).
## Each rank adds -42 to jump velocity (~10% of BASE_JUMP_VELOCITY of -420).
func get_jump_height_bonus() -> float:
	return perk_ranks.get("agility", 0) * -42.0

## Number of extra air jumps granted by Double Jump perk (0 = no double jump).
func get_extra_air_jumps() -> int:
	return perk_ranks.get("double_jump", 0)

## Fall damage reduction fraction from Soft Landing perk (0.0–0.50).
## Multiply fall damage by (1.0 - get_fall_damage_reduction()).
func get_fall_damage_reduction() -> float:
	return perk_ranks.get("soft_landing", 0) * 0.10

## Sprint speed multiplier from Momentum perk (1.0 = no bonus).
## Applied on top of the base SPRINT_MULT in PlayerProbe.
func get_sprint_speed_mult() -> float:
	return 1.0 + perk_ranks.get("momentum", 0) * 0.20

## Magnet attraction radius in pixels (0 when trinket not equipped).
func get_magnet_range() -> float:
	return 256.0 if trinket_magnet else 0.0  # 4 tiles × 64 px

func consume_energy(amount: int) -> bool:
	current_energy -= amount
	if current_energy < 0:
		current_energy = 0
	EventBus.energy_changed.emit(current_energy, get_max_energy())
	return current_energy > 0

func restore_energy(amount: int) -> void:
	current_energy = min(current_energy + amount, get_max_energy())
	EventBus.energy_changed.emit(current_energy, get_max_energy())

func reenergy_completely(cost_copper: int) -> bool:
	if run_coins >= cost_copper:
		run_coins -= cost_copper
		current_energy = get_max_energy()
		EventBus.coins_changed.emit(run_coins)
		EventBus.energy_changed.emit(current_energy, get_max_energy())
		return true
	return false

func is_out_of_energy() -> bool:
	return current_energy <= 0

# ---------------------------------------------------------------------------
# XP and Perk Tree
# ---------------------------------------------------------------------------

## Add XP to the player.  Handles per-save and global level-ups automatically.
func add_xp(amount: int) -> void:
	var xp_gained: int = maxi(1, roundi(amount * 0.3))
	player_xp += xp_gained
	_process_level_ups()
	EventBus.xp_changed.emit(player_xp, PerkSystem.xp_for_next_level(player_level))
	global_player_xp += xp_gained
	_process_global_level_ups()
	EventBus.global_xp_changed.emit(global_player_xp, PerkSystem.xp_for_next_level(global_player_level))
	SaveManager.save_global_progress()

func _process_level_ups() -> void:
	var threshold := PerkSystem.xp_for_next_level(player_level)
	while player_xp >= threshold:
		player_xp -= threshold
		player_level += 1
		perk_points += 1
		SaveManager.save_active_slot()
		EventBus.player_leveled_up.emit(player_level, perk_points)
		threshold = PerkSystem.xp_for_next_level(player_level)

func _process_global_level_ups() -> void:
	var threshold := PerkSystem.xp_for_next_level(global_player_level)
	while global_player_xp >= threshold:
		global_player_xp -= threshold
		global_player_level += 1
		EventBus.global_player_leveled_up.emit(global_player_level)
		threshold = PerkSystem.xp_for_next_level(global_player_level)

## Award XP to the global level only (no per-save player_xp).
## Used by the playtime incentive to avoid inflating run-scoped perk progress.
func _add_global_xp_only(amount: int) -> void:
	global_player_xp += amount
	_process_global_level_ups()
	EventBus.global_xp_changed.emit(global_player_xp, PerkSystem.xp_for_next_level(global_player_level))
	SaveManager.save_global_progress()

## Spend one perk point on a perk.  Returns true on success.
func spend_perk_point(perk_id: String) -> bool:
	if not PerkSystem.can_rank_up(perk_id, perk_ranks, perk_points):
		return false
	perk_ranks[perk_id] = perk_ranks.get(perk_id, 0) + 1
	perk_points -= 1
	SaveManager.save_active_slot()
	EventBus.perk_points_changed.emit(perk_points)
	return true

## Purchase one rank of a perk using coins (minerals).  Returns true on success.
func purchase_perk(perk_id: String) -> bool:
	if not PerkSystem.can_purchase(perk_id, perk_ranks, coins):
		return false
	var p := PerkSystem.get_perk(perk_id)
	var cost: int = p.get("mineral_cost", 0)
	perk_ranks[perk_id] = perk_ranks.get(perk_id, 0) + 1
	coins -= cost
	SaveManager.save_active_slot()
	EventBus.coins_changed.emit(coins)
	return true

func mark_tier_completed(node_type: int) -> void:
	# Record that a specific tier has been completed
	if node_type == 1:  # MapNode.NodeType.MINE
		has_completed_tier_1_mine = true
	elif node_type == 3:  # MapNode.NodeType.SETTLEMENT
		has_completed_tier_2_settlement = true
	save_game()

func save_game() -> void:
	var save_data = {
		"coins": coins,
		"carapace_level": carapace_level,
		"legs_level": legs_level,
		"mandibles_level": mandibles_level,
		"mineral_sense_level": mineral_sense_level,
		"claws_level": claws_level,
		"ladder_climb_speed_level": ladder_climb_speed_level,
		"mining_reach_level": mining_reach_level,
		"settlement_energy_bonus": settlement_energy_bonus,
		"settlement_forager_bonus": settlement_forager_bonus,
		"settlement_shroom_charges": settlement_shroom_charges,
		"settlement_mandible_bonus": settlement_mandible_bonus,
		"gem_count": gem_count,
		"carapace_gem_socketed": carapace_gem_socketed,
		"legs_gem_socketed": legs_gem_socketed,
		"mandibles_gem_socketed": mandibles_gem_socketed,
		"sense_gem_socketed": sense_gem_socketed,
		"total_coins_banked": total_coins_banked,
		"bosses_defeated_total": bosses_defeated_total,
		"deepest_row_reached": deepest_row_reached,
		"warp_drive_built": warp_drive_built,
		"cargo_bay_built": cargo_bay_built,
		"long_scanner_built": long_scanner_built,
		"gem_refinery_built": gem_refinery_built,
		"trade_amplifier_built": trade_amplifier_built,
		"debt_paid": debt_paid,
		"ladder_count": ladder_count,
		"equipped_leaf": equipped_leaf,
		"equipped_ice": equipped_ice,
		"equipped_companions": equipped_companions,
		"cat_color": cat_color.to_html(),
		"cat_outline_color": cat_outline_color.to_html(),
		"has_completed_tier_1_mine": has_completed_tier_1_mine,
		"has_completed_tier_2_settlement": has_completed_tier_2_settlement,
		"has_seen_overworld_hint": has_seen_overworld_hint,
		"has_completed_first_run": has_completed_first_run,
		"has_seen_intro": has_seen_intro,
		"trinket_paraglider": trinket_paraglider,
		"trinket_jet_boots": trinket_jet_boots,
		"trinket_stone_of_regen": trinket_stone_of_regen,
		"trinket_spring_boots": trinket_spring_boots,
		"trinket_jumping_bean": trinket_jumping_bean,
		"trinket_sneakers": trinket_sneakers,
		"trinket_gecko_gloves": trinket_gecko_gloves,
		"trinket_boots_of_sprinting": trinket_boots_of_sprinting,
		"trinket_cube_of_curing": trinket_cube_of_curing,
		"trinket_scuba_helmet": trinket_scuba_helmet,
		"trinket_magnet": trinket_magnet,
		"trinket_cosmic_radiation": trinket_cosmic_radiation,
		"trinket_curse_of_core": trinket_curse_of_core,
	}

	SaveManager.save_active_slot()

	var file = FileAccess.open(SAVE_PATH, FileAccess.WRITE)
	if file:
		file.store_string(JSON.stringify(save_data))
		file.close()

func load_game() -> void:
	if not FileAccess.file_exists(SAVE_PATH):
		return
	
	var file = FileAccess.open(SAVE_PATH, FileAccess.READ)
	if file:
		var json_string = file.get_as_text()
		file.close()
		
		var json = JSON.new()
		var error = json.parse(json_string)
		if error == OK:
			var data = json.data
			# Migrate legacy saves that stored mineral_currency + dollars separately
			var legacy_minerals: int = data.get("mineral_currency", 0)
			var legacy_dollars: int = data.get("dollars", 0)
			coins = data.get("coins", legacy_minerals * 100 + legacy_dollars * 100)
			carapace_level = data.get("carapace_level", 0)
			legs_level = data.get("legs_level", 0)
			mandibles_level = data.get("mandibles_level", 0)
			mineral_sense_level = data.get("mineral_sense_level", 0)
			claws_level = data.get("claws_level", 0)
			ladder_climb_speed_level = data.get("ladder_climb_speed_level", 0)
			mining_reach_level = data.get("mining_reach_level", 0)
			settlement_energy_bonus = data.get("settlement_energy_bonus", 0)
			settlement_forager_bonus = data.get("settlement_forager_bonus", 0)
			settlement_shroom_charges = data.get("settlement_shroom_charges", 0)
			settlement_mandible_bonus = data.get("settlement_mandible_bonus", 0)
			gem_count = data.get("gem_count", 0)
			carapace_gem_socketed = data.get("carapace_gem_socketed", false)
			legs_gem_socketed = data.get("legs_gem_socketed", false)
			mandibles_gem_socketed = data.get("mandibles_gem_socketed", false)
			sense_gem_socketed = data.get("sense_gem_socketed", false)
			total_coins_banked = data.get("total_coins_banked", data.get("total_minerals_banked", 0) * 100)
			bosses_defeated_total = data.get("bosses_defeated_total", 0)
			deepest_row_reached = data.get("deepest_row_reached", 0)
			warp_drive_built = data.get("warp_drive_built", false)
			cargo_bay_built = data.get("cargo_bay_built", false)
			long_scanner_built = data.get("long_scanner_built", false)
			gem_refinery_built = data.get("gem_refinery_built", false)
			trade_amplifier_built = data.get("trade_amplifier_built", false)
			debt_paid = data.get("debt_paid", 0)
			ladder_count = data.get("ladder_count", 0)
			equipped_leaf = data.get("equipped_leaf", false)
			equipped_ice = data.get("equipped_ice", false)
			var saved_companions: Variant = data.get("equipped_companions", {})
			equipped_companions = saved_companions if saved_companions is Dictionary else {}
			var color_html: String = data.get("cat_color", "")
			if color_html != "":
				cat_color = Color.from_string(color_html, Color.WHITE)
			else:
				cat_color = Color.WHITE
			var outline_html: String = data.get("cat_outline_color", "")
			if outline_html != "":
				cat_outline_color = Color.from_string(outline_html, Color("2b222a"))
			else:
				cat_outline_color = Color("2b222a")
			has_completed_tier_1_mine = data.get("has_completed_tier_1_mine", false)
			has_completed_tier_2_settlement = data.get("has_completed_tier_2_settlement", false)
			has_seen_overworld_hint = data.get("has_seen_overworld_hint", false)
			has_completed_first_run = data.get("has_completed_first_run", false)
			has_seen_intro = data.get("has_seen_intro", false)
			trinket_paraglider = data.get("trinket_paraglider", false)
			trinket_jet_boots = data.get("trinket_jet_boots", false)
			trinket_stone_of_regen = data.get("trinket_stone_of_regen", false)
			trinket_spring_boots = data.get("trinket_spring_boots", false)
			trinket_jumping_bean = data.get("trinket_jumping_bean", false)
			trinket_sneakers = data.get("trinket_sneakers", false)
			trinket_gecko_gloves = data.get("trinket_gecko_gloves", false)
			trinket_boots_of_sprinting = data.get("trinket_boots_of_sprinting", false)
			trinket_cube_of_curing = data.get("trinket_cube_of_curing", false)
			trinket_scuba_helmet = data.get("trinket_scuba_helmet", false)
			trinket_magnet = data.get("trinket_magnet", false)
			trinket_cosmic_radiation = data.get("trinket_cosmic_radiation", false)
			trinket_curse_of_core = data.get("trinket_curse_of_core", false)
			pass
		else:
			push_warning("GameManager: Failed to parse save file")
