extends Node

enum GameState {
	MENU,
	PLAYING,
	PAUSED,
	GAME_OVER
}

var current_state: GameState = GameState.MENU
var mineral_currency: int = 0
var run_mineral_currency: int = 0
var dollars: int = 0  # Persistent currency earned by selling bars at the smeltery
# Per-ore tracking for run summary (tile_type_id -> count/minerals)
var run_ore_counts: Dictionary = {}
var run_ore_earnings: Dictionary = {}
# Total individual ore chunks collected this run (used for capacity display)
var run_ore_chunk_count: int = 0
# Per-ore-type chunk counts (chunks physically picked up, used for inventory display)
var run_ore_chunk_counts: Dictionary = {}

# Base inventory slots per run (each ore chunk collected occupies one slot).
# Expanded by Cargo Bay spaceship upgrade and Claws (mandibles) upgrades.
const BASE_INVENTORY_SLOTS: int = 20
# Maximum number of same-type ore chunks that stack into a single inventory slot.
const STACK_SIZE: int = 32
var last_overworld_node_name: String = ""
## Path of the scene currently loaded — used by drop-in logic to route a late-joining guest
## to the same location as the host rather than always sending them to the overworld.
var current_scene_path: String = ""

# Ores allowed to spawn in the current level instance (set from MapNode.ore_types).
# Empty array means all ores can spawn (default behaviour).
var allowed_ore_types: Array = []

# Hazard types allowed to spawn in the current level instance (set from MapNode.hazard_types).
# Empty array means all hazards can spawn (default behaviour).
var allowed_hazard_types: Array = []

# Animal type for the current mine — host picks randomly and syncs to guest so
# both players see identical animals on the planet surface.
var planet_animal_type: String = ""

# Terrain generation seed for the current mine run — generated by the host and
# synced to the guest so both machines produce an identical tile layout.
var terrain_seed: int = 0

# Sky colour for the mining level — sampled from the average pixel colour of the
# selected mine node's planet sprite (set in Overworld._on_modal_confirmed).
# MiningLevel._draw() uses it to tint the sky strip and underground gradient.
var sky_color: Color = Color(0.40, 0.65, 0.90)

# Energy system
var current_energy: int = 100

func get_max_energy() -> int:
	return 100 + (legs_level * 25) + (25 if legs_gem_socketed else 0)

# Settlement carry-over bonuses (applied on next mine entry, then cleared)
var settlement_energy_bonus: int = 0       # extra starting energy from Energy Cache purchase
var settlement_forager_bonus: int = 0    # kept for save compatibility; unused since ForagerSystem removed
var settlement_shroom_charges: int = 0   # Mining Shroom charges pre-purchased
var settlement_mandible_bonus: int = 0   # temporary +N mandible power for one run

# Ladder count — persists across sessions; decremented each time player places a ladder
var ladder_count: int = 10
# Guest's ladder inventory in multiplayer — tracked on the host machine for authoritative validation.
# On the guest machine, ladder_count itself serves as the guest's personal inventory.
var guest_ladder_count: int = 10

# Currently selected hotbar slot: 0 = pickaxe, 1 = ladder, 2–9 = empty
var selected_hotbar_slot: int = 0

# Equipped followers (independent toggles)
var equipped_leaf: bool = false
var equipped_ice: bool = false

# Cat customization — sprite tint color (default white = no tint)
var cat_color: Color = Color.WHITE

# Upgrade levels
var carapace_level: int = 0
var legs_level: int = 0
var mandibles_level: int = 0
var mineral_sense_level: int = 0
var claws_level: int = 0
var ladder_climb_speed_level: int = 0
var mining_reach_level: int = 0

# Gem socketing system — gems collected as items, socketed for passive bonuses
var gem_count: int = 0                       # unspent gems in the colony's stockpile
const GEM_SOCKET_COST: int = 3              # gems required to fill one socket slot
var carapace_gem_socketed: bool = false      # +1 max HP
var legs_gem_socketed: bool = false          # +25 max energy, +15 move speed
var mandibles_gem_socketed: bool = false     # +4 mining power
var sense_gem_socketed: bool = false         # +3 sonar ping radius

# Spaceship Upgrade system — permanent ship upgrades unlocked by milestone conditions.
# Unlock conditions are checked at runtime; build costs are spent from dollars.
const SHIP_COST_WARP_DRIVE: int       = 200   # unlocks when total_minerals_banked >= 500
const SHIP_COST_CARGO_BAY: int        = 150   # unlocks when bosses_defeated_total >= 1
const SHIP_COST_LONG_SCANNER: int     = 300   # unlocks when total_minerals_banked >= 1000
const SHIP_COST_GEM_REFINERY: int     = 250   # unlocks when total_fossils >= 10
const SHIP_COST_TRADE_AMPLIFIER: int  = 200   # unlocks when deepest_row_reached >= 96

# Cumulative milestone trackers (persisted to save)
var total_minerals_banked: int = 0       # sum of all currency ever banked
var bosses_defeated_total: int = 0       # total boss encounters won
var total_fossils: int = 0               # total fossils found across all runs
var deepest_row_reached: int = 0         # deepest grid row ever reached
var total_playtime_seconds: float = 0.0  # total seconds played (accumulated while PLAYING)

# Spaceship upgrade built flags (persisted to save)
var warp_drive_built: bool = false       # 2x caravan travel speed on overworld
var cargo_bay_built: bool = false        # +25 ore carrying capacity per run
var long_scanner_built: bool = false     # always show both asteroid mines on overworld
var gem_refinery_built: bool = false     # +1 bonus gem per gem ore mined
var trade_amplifier_built: bool = false  # +25% dollar payout when selling bars

# Planet progression tracking (persisted to save)
var has_completed_tier_1_mine: bool = false       # True when player completes any Mine 1/2/3
var has_completed_tier_2_settlement: bool = false # True when player completes any Settlement 3/4

# Current node type for the active mine/settlement run (transient, not persisted)
var current_node_type: int = 0  # MapNode.NodeType value of the node being mined/visited

const SAVE_PATH = "user://save_data.json"

func _ready() -> void:
	print("GameManager initialized")
	# Legacy load_game() removed — SaveManager now handles slot-based persistence.
	# On first boot, SaveManager._migrate_legacy_save() imports the old file.
	NetworkManager.guest_connected.connect(_on_guest_connected)
	get_tree().set_auto_accept_quit(false)

func _notification(what: int) -> void:
	if what == NOTIFICATION_WM_CLOSE_REQUEST:
		if SaveManager.active_slot >= 0:
			SaveManager.save_active_slot()
		get_tree().quit()

func _process(delta: float) -> void:
	if current_state == GameState.PLAYING:
		total_playtime_seconds += delta

func add_currency(amount: int) -> void:
	run_mineral_currency += amount
	EventBus.minerals_changed.emit(run_mineral_currency)

func add_dollars(amount: int) -> void:
	dollars += amount
	EventBus.dollars_changed.emit(dollars)
	save_game()

func track_ore_mined(tile_type: int, minerals: int) -> void:
	run_ore_counts[tile_type] = run_ore_counts.get(tile_type, 0) + 1
	run_ore_earnings[tile_type] = run_ore_earnings.get(tile_type, 0) + minerals

func track_ore_chunk_collected() -> void:
	run_ore_chunk_count += 1

func track_ore_chunk_collected_by_type(ore_type: int) -> void:
	run_ore_chunk_count += 1
	run_ore_chunk_counts[ore_type] = run_ore_chunk_counts.get(ore_type, 0) + 1

func bank_currency() -> void:
	total_minerals_banked += run_mineral_currency
	mineral_currency += run_mineral_currency
	run_mineral_currency = 0
	EventBus.minerals_changed.emit(0)

func change_state(new_state: GameState) -> void:
	current_state = new_state
	EventBus.game_state_changed.emit(current_state)
	print("Game State Changed to: ", new_state)

func start_game() -> void:
	change_state(GameState.PLAYING)
	# In multiplayer, host sends upgrade state to guest before loading overworld
	if NetworkManager.is_multiplayer_session and NetworkManager.is_host and NetworkManager.guest_peer_id > 0:
		rpc_start_game_as_guest.rpc_id(NetworkManager.guest_peer_id,
			carapace_level, legs_level, mandibles_level, mineral_sense_level, claws_level,
			ladder_climb_speed_level, mining_reach_level,
			carapace_gem_socketed, legs_gem_socketed, mandibles_gem_socketed, sense_gem_socketed,
			warp_drive_built, cargo_bay_built, long_scanner_built, gem_refinery_built, trade_amplifier_built)
	load_overworld()

## Called on guest by host to apply kit/upgrade state before the game starts.
## Scene loading is handled separately by rpc_load_overworld_as_guest, which is
## sent immediately after this RPC via load_overworld().  Keeping state sync and
## scene loading in separate RPCs prevents the guest from loading Overworld twice.
@rpc("authority", "call_remote", "reliable")
func rpc_start_game_as_guest(carapace_lvl: int, legs_lvl: int, mandibles_lvl: int,
		mineral_sense_lvl: int, claws_lvl: int, ladder_climb_lvl: int, mining_reach_lvl: int,
		carapace_gem: bool, legs_gem: bool, mandibles_gem: bool, sense_gem: bool,
		warp: bool, cargo: bool, scanner: bool, refinery: bool, amplifier: bool) -> void:
	carapace_level = carapace_lvl
	legs_level = legs_lvl
	mandibles_level = mandibles_lvl
	mineral_sense_level = mineral_sense_lvl
	claws_level = claws_lvl
	ladder_climb_speed_level = ladder_climb_lvl
	mining_reach_level = mining_reach_lvl
	carapace_gem_socketed = carapace_gem
	legs_gem_socketed = legs_gem
	mandibles_gem_socketed = mandibles_gem
	sense_gem_socketed = sense_gem
	warp_drive_built = warp
	cargo_bay_built = cargo
	long_scanner_built = scanner
	gem_refinery_built = refinery
	trade_amplifier_built = amplifier
	EventBus.multiplayer_guest_kit_updated.emit()
	change_state(GameState.PLAYING)
	# Scene transition handled by the following rpc_load_overworld_as_guest call

## Drop-in: called when a guest connects while the host is already in-game.
## Sends the guest the host's kit and routes them to the host's current location.
func _on_guest_connected(peer_id: int) -> void:
	if not NetworkManager.is_host or current_state != GameState.PLAYING:
		return
	if "MiningLevel" in current_scene_path:
		# Host is mid-mine — send guest directly into the same mine.
		rpc_drop_in_to_mine_as_guest.rpc_id(peer_id,
			carapace_level, legs_level, mandibles_level, mineral_sense_level, claws_level,
			ladder_climb_speed_level, mining_reach_level,
			carapace_gem_socketed, legs_gem_socketed, mandibles_gem_socketed, sense_gem_socketed,
			warp_drive_built, cargo_bay_built, long_scanner_built, gem_refinery_built, trade_amplifier_built,
			current_scene_path, current_energy,
			sky_color.r, sky_color.g, sky_color.b,
			allowed_ore_types, allowed_hazard_types,
			planet_animal_type, terrain_seed)
	else:
		# Host is on the overworld (or a settlement) — sync kit then load the
		# overworld on the guest.  Planet config (names, positions, sprite frames)
		# is synced via the request/response already built into Overworld._ready():
		# the guest calls rpc_request_planet_config once its scene is ready, and
		# the host responds with rpc_apply_planet_config.
		rpc_start_game_as_guest.rpc_id(peer_id,
			carapace_level, legs_level, mandibles_level, mineral_sense_level, claws_level,
			ladder_climb_speed_level, mining_reach_level,
			carapace_gem_socketed, legs_gem_socketed, mandibles_gem_socketed, sense_gem_socketed,
			warp_drive_built, cargo_bay_built, long_scanner_built, gem_refinery_built, trade_amplifier_built)
		rpc_load_overworld_as_guest.rpc_id(peer_id)

func pause_game() -> void:
	change_state(GameState.PAUSED)

func lose_run() -> void:
	run_mineral_currency = 0
	run_ore_counts.clear()
	run_ore_earnings.clear()
	run_ore_chunk_count = 0
	run_ore_chunk_counts.clear()
	EventBus.minerals_changed.emit(0)
	# Clear planet config so the overworld re-randomizes on next visit
	if not NetworkManager.is_multiplayer_session or NetworkManager.is_host:
		SaveManager.clear_active_slot_run_data()
	if NetworkManager.is_multiplayer_session and NetworkManager.is_host and NetworkManager.guest_peer_id > 0:
		rpc_lose_run_as_guest.rpc_id(NetworkManager.guest_peer_id)
	await _transition_to_scene("res://src/levels/Overworld.tscn")

@rpc("authority", "call_remote", "reliable")
func rpc_lose_run_as_guest() -> void:
	run_mineral_currency = 0
	run_ore_counts.clear()
	run_ore_earnings.clear()
	run_ore_chunk_count = 0
	run_ore_chunk_counts.clear()
	EventBus.minerals_changed.emit(0)
	await _transition_to_scene("res://src/levels/Overworld.tscn")

func complete_run() -> void:
	if NetworkManager.is_multiplayer_session and NetworkManager.is_host and NetworkManager.guest_peer_id > 0:
		rpc_complete_run_as_guest.rpc_id(NetworkManager.guest_peer_id, run_mineral_currency)
	var summary_scene = load("res://src/ui/RunSummary.tscn")
	var summary = summary_scene.instantiate()
	get_tree().root.add_child(summary)
	# Note: RunSummary handles banking and returning to Overworld

@rpc("authority", "call_remote", "reliable")
func rpc_complete_run_as_guest(final_minerals: int) -> void:
	run_mineral_currency = final_minerals
	EventBus.minerals_changed.emit(run_mineral_currency)
	var summary_scene = load("res://src/ui/RunSummary.tscn")
	var summary = summary_scene.instantiate()
	get_tree().root.add_child(summary)

func load_mining_level(scene_path: String = "") -> void:
	run_mineral_currency = 0 # Reset run currency on entry
	run_ore_counts.clear()
	run_ore_earnings.clear()
	run_ore_chunk_count = 0
	run_ore_chunk_counts.clear()
	current_energy = get_max_energy() # Reset energy on entry

	# Apply settlement carry-over bonuses then clear them
	if settlement_energy_bonus > 0:
		current_energy = mini(current_energy + settlement_energy_bonus, get_max_energy() + settlement_energy_bonus)
		settlement_energy_bonus = 0
	# shroom / mandible / forager bonuses are consumed by MiningLevel on entry

	EventBus.minerals_changed.emit(0)
	EventBus.energy_changed.emit(current_energy, get_max_energy())
	var path := scene_path if scene_path != "" else "res://src/levels/MiningLevel.tscn"
	# Host generates the terrain seed and animal type so both can be synced to the guest.
	if NetworkManager.is_multiplayer_session and NetworkManager.is_host:
		var _types := ["Chicken", "Sheep", "Pig"]
		planet_animal_type = _types[randi() % _types.size()]
		terrain_seed = randi()
	elif not NetworkManager.is_multiplayer_session:
		terrain_seed = randi()
	# In multiplayer, tell guest to load the same mine with the same starting state
	if NetworkManager.is_multiplayer_session and NetworkManager.is_host and NetworkManager.guest_peer_id > 0:
		rpc_load_mine_as_guest.rpc_id(NetworkManager.guest_peer_id, path,
			current_energy, sky_color.r, sky_color.g, sky_color.b,
			allowed_ore_types, allowed_hazard_types,
			settlement_shroom_charges, settlement_mandible_bonus,
			planet_animal_type, terrain_seed)
	change_state(GameState.PLAYING)
	await _transition_to_scene(path)

## Guest RPC: mirror the host's mine-entry state then load the same level.
@rpc("authority", "call_remote", "reliable")
func rpc_load_mine_as_guest(path: String, start_energy: int,
		sky_r: float, sky_g: float, sky_b: float,
		ore_types: Array, hazard_types: Array,
		shroom_charges: int, mandible_bonus: int,
		animal_type: String, seed_value: int) -> void:
	run_mineral_currency = 0
	run_ore_counts.clear()
	run_ore_earnings.clear()
	run_ore_chunk_count = 0
	run_ore_chunk_counts.clear()
	current_energy = start_energy
	sky_color = Color(sky_r, sky_g, sky_b)
	allowed_ore_types = ore_types.duplicate()
	allowed_hazard_types = hazard_types.duplicate()
	settlement_shroom_charges = shroom_charges
	settlement_mandible_bonus = mandible_bonus
	planet_animal_type = animal_type
	terrain_seed = seed_value
	EventBus.minerals_changed.emit(0)
	EventBus.energy_changed.emit(current_energy, get_max_energy())
	await _transition_to_scene(path)

## Guest RPC: drop in to the host's active mine run mid-session.
## Applies the host's kit then loads the same MiningLevel the host is already in.
@rpc("authority", "call_remote", "reliable")
func rpc_drop_in_to_mine_as_guest(carapace_lvl: int, legs_lvl: int, mandibles_lvl: int,
		mineral_sense_lvl: int, claws_lvl: int, ladder_climb_lvl: int, mining_reach_lvl: int,
		carapace_gem: bool, legs_gem: bool, mandibles_gem: bool, sense_gem: bool,
		warp: bool, cargo: bool, scanner: bool, refinery: bool, amplifier: bool,
		mine_path: String, start_energy: int,
		sky_r: float, sky_g: float, sky_b: float,
		ore_types: Array, hazard_types: Array,
		animal_type: String, seed_value: int) -> void:
	carapace_level = carapace_lvl
	legs_level = legs_lvl
	mandibles_level = mandibles_lvl
	mineral_sense_level = mineral_sense_lvl
	claws_level = claws_lvl
	ladder_climb_speed_level = ladder_climb_lvl
	mining_reach_level = mining_reach_lvl
	carapace_gem_socketed = carapace_gem
	legs_gem_socketed = legs_gem
	mandibles_gem_socketed = mandibles_gem
	sense_gem_socketed = sense_gem
	warp_drive_built = warp
	cargo_bay_built = cargo
	long_scanner_built = scanner
	gem_refinery_built = refinery
	trade_amplifier_built = amplifier
	EventBus.multiplayer_guest_kit_updated.emit()
	run_mineral_currency = 0
	run_ore_counts.clear()
	run_ore_earnings.clear()
	run_ore_chunk_count = 0
	run_ore_chunk_counts.clear()
	current_energy = start_energy
	sky_color = Color(sky_r, sky_g, sky_b)
	allowed_ore_types = ore_types.duplicate()
	allowed_hazard_types = hazard_types.duplicate()
	planet_animal_type = animal_type
	terrain_seed = seed_value
	EventBus.minerals_changed.emit(0)
	EventBus.energy_changed.emit(current_energy, get_max_energy())
	change_state(GameState.PLAYING)
	await _transition_to_scene(mine_path)

func load_settlement_level(scene_path: String) -> void:
	# Visit a settlement without resetting run state — player keeps banked minerals
	change_state(GameState.PLAYING)
	await _transition_to_scene(scene_path)

func load_overworld() -> void:
	change_state(GameState.PLAYING)
	if NetworkManager.is_multiplayer_session and NetworkManager.is_host and NetworkManager.guest_peer_id > 0:
		rpc_load_overworld_as_guest.rpc_id(NetworkManager.guest_peer_id)
	await _transition_to_scene("res://src/levels/Overworld.tscn")

@rpc("authority", "call_remote", "reliable")
func rpc_load_overworld_as_guest() -> void:
	change_state(GameState.PLAYING)
	await _transition_to_scene("res://src/levels/Overworld.tscn")

func _transition_to_scene(scene_path: String) -> void:
	await SceneTransition.fade_to_black(0.5)
	current_scene_path = scene_path
	get_tree().change_scene_to_file(scene_path)
	await get_tree().create_timer(0.1).timeout
	await SceneTransition.fade_from_black(0.5)

func upgrade_carapace() -> void:
	carapace_level += 1
	save_game()
	print("Spacesuit reinforced to level ", carapace_level)

func upgrade_legs() -> void:
	legs_level += 1
	save_game()
	print("Jet Boots upgraded to level ", legs_level)

func upgrade_mandibles() -> void:
	mandibles_level += 1
	save_game()
	EventBus.minerals_changed.emit(run_mineral_currency)
	print("Cargo hold expanded to level ", mandibles_level)

func upgrade_mineral_sense() -> void:
	mineral_sense_level += 1
	save_game()
	print("Space Whiskers tuned to level ", mineral_sense_level)

func upgrade_claws() -> void:
	claws_level += 1
	save_game()
	print("Claws sharpened to level ", claws_level)

func upgrade_ladder_climb_speed() -> void:
	ladder_climb_speed_level += 1
	save_game()
	print("Ladder climbing speed upgraded to level ", ladder_climb_speed_level)

func upgrade_mining_reach() -> void:
	mining_reach_level += 1
	save_game()
	print("Mining reach expanded to level ", mining_reach_level)

func get_sonar_ping_radius() -> float:
	return 4.0 + mineral_sense_level * 3.0 + (3.0 if sense_gem_socketed else 0.0)

## Number of inventory slots available per run (slot-based; each ore chunk uses one slot).
## Boosted by Cargo Bay spaceship upgrade and Claws (mandibles) upgrades.
func get_ore_capacity() -> int:
	return BASE_INVENTORY_SLOTS + (5 if cargo_bay_built else 0) + (mandibles_level * 2) + (2 if mandibles_gem_socketed else 0)

## Number of slots currently occupied, counting stacks of up to STACK_SIZE chunks per slot.
## Same ore type chunks stack together; one slot holds up to STACK_SIZE of a single type.
func get_stacked_slots_used() -> int:
	var total: int = 0
	for count: int in run_ore_chunk_counts.values():
		total += ceili(float(count) / float(STACK_SIZE))
	return total

## Returns true when every inventory slot is occupied and no more ore can be picked up.
func is_inventory_full() -> bool:
	return get_stacked_slots_used() >= get_ore_capacity()

## Caravan travel speed multiplier on the overworld (boosted by Warp Drive).
func get_ship_speed_mult() -> float:
	return 2.0 if warp_drive_built else 1.0

## Bonus gems awarded per gem ore mined (boosted by Gem Refinery).
func get_gem_mine_bonus() -> int:
	return 1 if gem_refinery_built else 0

## Dollar sell multiplier for smeltery bars (boosted by Trade Amplifier).
func get_dollar_sell_mult() -> float:
	return 1.25 if trade_amplifier_built else 1.0

func get_sonar_ping_energy_cost() -> int:
	return maxi(1, ceili((5 - mineral_sense_level) / 2.0))

func get_ladder_climb_speed() -> float:
	return 420.0 + (ladder_climb_speed_level * 50.0)

func get_mining_reach() -> float:
	return 4.5 + (mining_reach_level * 0.75)

func get_max_health() -> int:
	return 3 + carapace_level + (1 if carapace_gem_socketed else 0)

func get_max_speed() -> float:
	return 300.0 + (legs_level * 30.0) + (15.0 if legs_gem_socketed else 0.0)

func get_mandibles_power() -> int:
	return 5 + claws_level * 3

func consume_energy(amount: int) -> bool:
	current_energy -= amount
	if current_energy < 0:
		current_energy = 0
	EventBus.energy_changed.emit(current_energy, get_max_energy())
	return current_energy > 0

func restore_energy(amount: int) -> void:
	current_energy = min(current_energy + amount, get_max_energy())
	EventBus.energy_changed.emit(current_energy, get_max_energy())

func reenergy_completely(cost: int) -> bool:
	if run_mineral_currency >= cost:
		run_mineral_currency -= cost
		current_energy = get_max_energy()
		EventBus.minerals_changed.emit(run_mineral_currency)
		EventBus.energy_changed.emit(current_energy, get_max_energy())
		return true
	return false

func is_out_of_energy() -> bool:
	return current_energy <= 0

func mark_tier_completed(node_type: int) -> void:
	# Record that a specific tier has been completed
	if node_type == 1:  # MapNode.NodeType.MINE
		has_completed_tier_1_mine = true
	elif node_type == 3:  # MapNode.NodeType.SETTLEMENT
		has_completed_tier_2_settlement = true
	save_game()

func save_game() -> void:
	var save_data = {
		"mineral_currency": mineral_currency,
		"dollars": dollars,
		"carapace_level": carapace_level,
		"legs_level": legs_level,
		"mandibles_level": mandibles_level,
		"mineral_sense_level": mineral_sense_level,
		"claws_level": claws_level,
		"ladder_climb_speed_level": ladder_climb_speed_level,
		"mining_reach_level": mining_reach_level,
		"settlement_energy_bonus": settlement_energy_bonus,
		"settlement_forager_bonus": settlement_forager_bonus,
		"settlement_shroom_charges": settlement_shroom_charges,
		"settlement_mandible_bonus": settlement_mandible_bonus,
		"gem_count": gem_count,
		"carapace_gem_socketed": carapace_gem_socketed,
		"legs_gem_socketed": legs_gem_socketed,
		"mandibles_gem_socketed": mandibles_gem_socketed,
		"sense_gem_socketed": sense_gem_socketed,
		"total_minerals_banked": total_minerals_banked,
		"bosses_defeated_total": bosses_defeated_total,
		"total_fossils": total_fossils,
		"deepest_row_reached": deepest_row_reached,
		"warp_drive_built": warp_drive_built,
		"cargo_bay_built": cargo_bay_built,
		"long_scanner_built": long_scanner_built,
		"gem_refinery_built": gem_refinery_built,
		"trade_amplifier_built": trade_amplifier_built,
		"ladder_count": ladder_count,
		"equipped_leaf": equipped_leaf,
		"equipped_ice": equipped_ice,
		"cat_color": cat_color.to_html(),
		"has_completed_tier_1_mine": has_completed_tier_1_mine,
		"has_completed_tier_2_settlement": has_completed_tier_2_settlement,
	}

	SaveManager.save_active_slot()
	print("Game saved (slot %d)" % SaveManager.active_slot)
  
	var file = FileAccess.open(SAVE_PATH, FileAccess.WRITE)
	if file:
		file.store_string(JSON.stringify(save_data))
		file.close()
		print("Game saved")

func load_game() -> void:
	if not FileAccess.file_exists(SAVE_PATH):
		print("No save file found")
		return
	
	var file = FileAccess.open(SAVE_PATH, FileAccess.READ)
	if file:
		var json_string = file.get_as_text()
		file.close()
		
		var json = JSON.new()
		var error = json.parse(json_string)
		if error == OK:
			var data = json.data
			mineral_currency = data.get("mineral_currency", 0)
			dollars = data.get("dollars", 0)
			carapace_level = data.get("carapace_level", 0)
			legs_level = data.get("legs_level", 0)
			mandibles_level = data.get("mandibles_level", 0)
			mineral_sense_level = data.get("mineral_sense_level", 0)
			claws_level = data.get("claws_level", 0)
			ladder_climb_speed_level = data.get("ladder_climb_speed_level", 0)
			mining_reach_level = data.get("mining_reach_level", 0)
			settlement_energy_bonus = data.get("settlement_energy_bonus", 0)
			settlement_forager_bonus = data.get("settlement_forager_bonus", 0)
			settlement_shroom_charges = data.get("settlement_shroom_charges", 0)
			settlement_mandible_bonus = data.get("settlement_mandible_bonus", 0)
			gem_count = data.get("gem_count", 0)
			carapace_gem_socketed = data.get("carapace_gem_socketed", false)
			legs_gem_socketed = data.get("legs_gem_socketed", false)
			mandibles_gem_socketed = data.get("mandibles_gem_socketed", false)
			sense_gem_socketed = data.get("sense_gem_socketed", false)
			total_minerals_banked = data.get("total_minerals_banked", 0)
			bosses_defeated_total = data.get("bosses_defeated_total", 0)
			total_fossils = data.get("total_fossils", 0)
			deepest_row_reached = data.get("deepest_row_reached", 0)
			warp_drive_built = data.get("warp_drive_built", false)
			cargo_bay_built = data.get("cargo_bay_built", false)
			long_scanner_built = data.get("long_scanner_built", false)
			gem_refinery_built = data.get("gem_refinery_built", false)
			trade_amplifier_built = data.get("trade_amplifier_built", false)
			ladder_count = data.get("ladder_count", 0)
			equipped_leaf = data.get("equipped_leaf", false)
			equipped_ice = data.get("equipped_ice", false)
			var color_html: String = data.get("cat_color", "")
			if color_html != "":
				cat_color = Color.from_string(color_html, Color.WHITE)
			else:
				cat_color = Color.WHITE
			has_completed_tier_1_mine = data.get("has_completed_tier_1_mine", false)
			has_completed_tier_2_settlement = data.get("has_completed_tier_2_settlement", false)
			print("Game loaded")
		else:
			print("Failed to parse save file")
